# Test configuration for HydraLance parameter completion
model:
  _target_: torch.nn.Linear
  # Try typing here - you should get parameter completions like:
  # in_features: 
  # out_features:
  # bias:

optimizer:
  _target_: torch.optim.Adam
  # Try typing here - you should get parameter completions like:
  # lr:
  # betas:
  # eps:
  # weight_decay:

# Another example with a different class
loss:
  _target_: torch.nn.CrossEntropyLoss
  # Try typing here for parameter completions

# Example with existing parameters (should be filtered out)
transform:
  _target_: torchvision.transforms.Resize
  size: 224
  # Try typing here - 'size' should not appear in completions since it's already defined
